#Q.1. WRITE A PROGRAM TO ADD TWO NUMBER
'''a = int (input("Enter your first number:"))
b = int (input("Enter your second number:"))
print(f"Sum of your given number = {a+b}")'''

#Q.2.WAP TO FIND REMANDER WHEN A NUMBER IS DEVIDED BY 2
'''n = int (input("Enter your number:"))
print(f"Remander = {n%2}")'''
#Q.3.CHECK THE TYPE OF THE VARIABLE ASSIGNED USING INPUT FUNCTION
'''n = input("Enter anything:")
#print(type(n))    
#n=int(n)
#print(type(n))
#n=float(n)
#print(type(n))'''

#Q.4. USE COMPERISON OPERATOR TO FIND A NUMBER GRETEST OR NOT 
'''
a = int (input ("Enter your first number :"))
b = int ( input ("Enter your second number :"))
if a==b :
    print(f"Given two number  is Equal")
elif a>b :
    print(f"{a} is greter than {b}")
else:
    print(f"{b} is grater than {a}")'''

#Q.5 WAP  TO FIND AVARAGE OF TWO NUMBER  
'''
a = int ( input("Enter our first number :"))
b = int ( input ("Enter your second number :"))
print(f"a = {a}\tand\tb = {b}")
d=(a+b)/2
print(f"Evarage of your given two number = {d}")    '''

#Q.6.WAP TO CALCULATE SQUARE OF A NUMBER

n = int (input ("Enter any number : "))
print(f"Square of your given number = {n**2}")
